version: '3'

services:
  server1:
    build: .
    ports:
      - "3001:3000"

  server2:
    build: .
    ports:
      - "3002:3000"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.copy
      - /etc/letsencrypt:/etc/letsencrypt
